version: '2'

services:
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - axelor
    environment:
      - POSTGRES_DB=axelor
      - POSTGRES_USER=axelor
      - POSTGRES_PASSWORD=axelor      
      - PGDATA=/var/lib/postgresql/data

  app:
    build: ./axelor
    image: axelor-jaco
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - app-data:/srv/axelor
    networks:
      - axelor
      - web
    environment:
      - VIRTUAL_HOST=${HOSTNAME}
      - LETSENCRYPT_HOST=${HOSTNAME}
      - LETSENCRYPT_EMAIL=${EMAIL}
      - VIRTUAL_PORT=8080
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=587
      - SMTP_CHANNEL=starttls
      - SMTP_USER_NAME=${SMTP_USER_NAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
   
volumes:
  app-data:
  db:

networks:
  axelor:
      driver: bridge
  web:
      external:
          name: web
